### ISSUE TITLE
Write user story

### ISSUE THREAD

**Issue by MatthewShahamad** [MatthewShahamad/Whos-App#3]
Link to users stories in [google doc](https://docs.google.com/document/d/1M3xLMyQnaR0ikwKRZaDOgDHf1gZgqqMdGAWjapoYJoo/edit) https://docs.google.com/document/d/1M3xLMyQnaR0ikwKRZaDOgDHf1gZgqqMdGAWjapoYJoo/edit

**Comment by miss-mad** [comment]
Done but might change so don't close yet
